---
title: "Data Wrangling 2"
author: "Ankita Guha"
date: "October 17, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(plyr)
library(dplyr)
library(ggplot2)
library(reshape2)
library(tidyr)
library(reader)
#library(lubridate)
```


```{r}
PGSurveyDomainQuestion <- read.table("PGSurveyDomainQuestion.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
PGSurveyDomainQuestion$X = NULL
PGSurveyDomainQuestion$SurveyCategoryID <- as.factor(PGSurveyDomainQuestion$SurveyCategoryID)
PGSurveyDomainQuestion$DomainID <- as.factor(PGSurveyDomainQuestion$DomainID)
PGSurveyDomainQuestion$QuestionID <- as.factor(PGSurveyDomainQuestion$QuestionID)
PGSurveyDomainQuestion$QuestionTypeID <- as.factor(PGSurveyDomainQuestion$QuestionTypeID)
PGSurveyDomainQuestion$SkipLogicAppliedQuestionTypeResponseID <- as.factor(PGSurveyDomainQuestion$SkipLogicAppliedQuestionTypeResponseID)

PGSurveyDomainQuestion %>% filter(QuestionTypeID == "11")
```



```{r}
QuestionType <-read.csv("QuestionType.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
QuestionType$Code = NULL

QuestionType$QuestionTypeID <- as.factor(QuestionType$QuestionTypeID)
```


```{r}
QuestionTypeResponse <- read.csv("QuestionTypeResponse.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
QuestionTypeResponse$X = NULL
QuestionTypeResponse$X.1 = NULL
QuestionTypeResponse$X.2 = NULL
QuestionTypeResponse$QuestionTypeResponseID = NULL


QuestionTypeResponse$QuestionTypeID <- as.factor(QuestionTypeResponse$QuestionTypeID)

QuestionTypeResponse = join(QuestionType, QuestionTypeResponse, by=c("QuestionTypeID"))
QuestionTypeResponse <- rename(QuestionTypeResponse, DescForQuesTypeID = Description)
write.csv(QuestionTypeResponse, "QuestionTypeResponseWithDescForQuestionType.csv")
```


```{r}
#PGSurveyDomainQuestion = join(QuestionType, PGSurveyDomainQuestion, by=c("QuestionTypeID"))
```




```{r}
library(RSQLite)
dbSource <- src_sqlite("sjmo.db")
dbSource
```

```{r}
QuestionTypeTab <- tbl(dbSource, "QuestionType")
QuestionTypeTab$QuestionTypeID = as.factor(QuestionTypeTab$QuestionTypeID)
QuestionTypeTab



QuestionTypeTab %>%
   select(QuestionTypeID, Description)



QuestionTypeResponseTab <- tbl(dbSource, "QuestionTypeResponse")
QuestionTypeResponseTab


QuestionTypeResponseTab %>% group_by(IsTopBox)
```

```{r}

```

