---
title: "Data Wrangling 3"
author: "Ankita Guha"
date: "October 17, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(plyr)
library(dplyr)
library(ggplot2)
library(reshape2)
library(tidyr)
library(reader)
#library(lubridate)
```


```{r}
PGSurveyDomainQuestion <- read.csv("PGSurveyDomainQuestion.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)


PGSurveyDomainQuestion$X = NULL

PGSurveyDomainQuestion %>%
  filter(QuestionID > 96)

PGSurveyDomainQuestion$SurveyCategoryID <- as.factor(PGSurveyDomainQuestion$SurveyCategoryID)
PGSurveyDomainQuestion$DomainID <- as.factor(PGSurveyDomainQuestion$DomainID)
PGSurveyDomainQuestion$QuestionTypeID <- as.factor(PGSurveyDomainQuestion$QuestionTypeID)
PGSurveyDomainQuestion$SkipLogicAppliedQuestionTypeResponseID <- as.factor(PGSurveyDomainQuestion$SkipLogicAppliedQuestionTypeResponseID)
```


```{r}
QuestionTypeResponseWithDesc <- read.csv("QuestionTypeResponseWithDescForQuestionType.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
QuestionTypeResponseWithDesc$X = NULL


QuestionTypeResponseWithDesc$QuestionTypeID <- as.factor(QuestionTypeResponseWithDesc$QuestionTypeID)
```


```{r}
QuestionTypeResponse = join(QuestionType, QuestionTypeResponse, by=c("QuestionTypeID"))
QuestionTypeResponse <- rename(QuestionTypeResponse, DescForQuesTypeID = Description)
write.csv(QuestionTypeResponse, "QuestionTypeResponseWithDescForQuestionType.csv")
```


```{r}
PGSurveyDomQuesQuesTypeResp = join(QuestionTypeResponseWithDesc, PGSurveyDomainQuestion, by=c("QuestionTypeID"))
```

```{r}
library(RSQLite)
dbSource1 <- src_sqlite("PatientSatisfactionSurvey.db")
dbSource1
```
```{r}
con <- DBI::dbConnect(RSQLite::SQLite(), path = ":PatientSatisfactionSurvey.db:")
```

```{r}
PS_db <- tbl(con, "PGSurveyDomainQuestion")
```

