---
title: "Data Wrangling 1_PressGaneyRaw1"
author: "Ankita Guha"
date: "October 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Let's load some of the libraries we'll need:

```{r}
library(plyr)
library(dplyr)
library(ggplot2)
library(reshape2)
library(tidyr)
library(reader)
#library(lubridate)
```



```{r}

#Reading our original dataframe
# PGRaw <- read.table("PGRaw 1.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
# View(PGRaw)
# 
# library(lubridate)
# ymd("20110604") 
# 
# #Date formatted according to the raw date type
# PGRaw$X = NULL
# PGRaw$AdmitDateLocal <- as.Date(ymd(PGRaw$AdmitDateLocal))
# PGRaw$DischargeDateLocal <- as.Date(ymd(PGRaw$DischargeDateLocal))
# PGRaw$RecordedDateLocal <- as.Date(ymd(PGRaw$RecordedDateLocal))
# 
# 
# PGRaw$SurveyCategoryID <- as.factor(PGRaw$SurveyCategoryID)
# PGRaw$DomainID <- as.factor(PGRaw$DomainID)
# PGRaw$QuestionID <- as.factor(PGRaw$QuestionID)
# PGRaw$QuestionTypeID <- as.factor(PGRaw$QuestionTypeID)
# PGRaw$SkipLogicAppliedQuestionTypeResponseID <- as.factor(PGRaw$SkipLogicAppliedQuestionTypeResponseID)
# 
# #Creates a subset of just the Survey Questionairre from the Press Ganey Survey
# PGSurvey <- PGRaw %>% select(3, 14:18)
# rm(PGSurvey)




#str(PGSurveyRefined1)

#PGSurveyRefined1$IsDefaultChoice=as.factor(PGSurveyRefined1$IsDefaultChoice)

#PGSurveyRefined1$IsDefaultChoice <- as.character(PGSurveyRefined1$IsDefaultChoice)


# View(PGSurveyRefined1)
# 
# unique(PGSurveyRefined1$IsDefaultChoice)
# 
# 
# #rm(PGSurveyRefined)
# rm(PGQuestion)
# rm(d3)
```

Reading all the dataframe for the next step of analysis:

```{r}
#Reading Data Table
PGSurveyRefined <- read.table("PGSurveyRefined 1.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
PGSurveyRefined <- rename(PGSurveyRefined, LongTextForDomain = LongText)
# str(PGSurveyRefined)
# View(PGSurveyRefined)

#Clearing some of the columns for sake of analysis
PGSurveyRefined$X = NULL
PGSurveyRefined$CAHPSID = NULL
PGSurveyRefined$HospitalNumber = NULL
PGSurveyRefined$Location = NULL
PGSurveyRefined$SurveyId = NULL
PGSurveyRefined$AdmittingADTID = NULL
PGSurveyRefined$AdmittingNPI = NULL
PGSurveyRefined$AttendingADTID = NULL
PGSurveyRefined$AttendingNPI = NULL
PGSurveyRefined$SubLocation = NULL

#View(PGSurveyRefined)

library(lubridate)
ymd("20110604") 

#Converting to Date datatype from character
PGSurveyRefined$AdmitDateLocal <- as.Date(ymd(PGSurveyRefined$AdmitDateLocal))
PGSurveyRefined$DischargeDateLocal <- as.Date(ymd(PGSurveyRefined$DischargeDateLocal))
PGSurveyRefined$RecordedDateLocal <- as.Date(ymd(PGSurveyRefined$RecordedDateLocal))

#Converting to factor from integer
PGSurveyRefined$SurveyCategoryID <- as.factor(PGSurveyRefined$SurveyCategoryID)
PGSurveyRefined$DomainID <- as.factor(PGSurveyRefined$DomainID)
PGSurveyRefined$QuestionID <- as.factor(PGSurveyRefined$QuestionID)
PGSurveyRefined$QuestionTypeID <- as.factor(PGSurveyRefined$QuestionTypeID)
PGSurveyRefined$SkipLogicAppliedQuestionTypeResponseID <- as.factor(PGSurveyRefined$SkipLogicAppliedQuestionTypeResponseID)

#View(PGSurveyRefined)

#Checking the df if thereis any value for QuestionTypeID value 8
PGSurveyRefined  %>%
    filter(QuestionTypeID == "8")


##Creates a subset of just the Survey Questionairre from the Press Ganey Survey
#PGSurvey1 <- PGSurveyRefined %>% select(2, 11:16)

#rm(PGRaw)
```

QuestionTypeID 7 and 8 is not present in the original Press Ganey Survey. Therefore removing the same from our data frame for ease of analysis. 

```{r}
#Reading Question from the Look Up Table
PGQuestion <- read.table("Question.csv", fill = TRUE, header = TRUE, quote = "\"", sep = ",", stringsAsFactors = FALSE, encoding="UTF-8") #This line helped to avoid the error EOF string. There was "\"" within the ShortText and LongText
PGQuestion <- rename(PGQuestion, ShortTextForQues = ShortText, LongTextForQues = LongText)



#Check how many rows we have in PGQuestion with QuestionTypeID as 7
# PGQuestion  %>%
#     filter(QuestionTypeID == "7")

#Okay, so looks like we just have 2 rows of value when QuestionTypeID is 7. Removing these two rows because in the main survey data, the variable column of QuestionTypeID with value 7 is absent. Therefore for ease of data merging it would be convinient to remove these two rows containing when the QuestionTypeID is equal to 7. 

#Dropping the Rows with QuestionTypeID value 7
PGQuestion<-PGQuestion[!(PGQuestion$QuestionTypeID=="7"),] 
#PGQuestion$QuestionTypeID == 7

#Looks like we have successfully removed the rows. Now that we have removed them we can go ahed and merge them with our dataframe of interest.





#Converting Data Type for ease of calculation
#PGQuestion$QuestionID <- as.factor(PGQuestion$QuestionID)
PGQuestion$QuestionTypeID <- as.factor(PGQuestion$QuestionTypeID)
PGQuestion$SurveyCategoryID <- as.factor(PGQuestion$SurveyCategoryID)
#PGQuestion$IsDefaultChoice=as.factor(PGQuestion$IsDefaultChoice) #Seems like the df is not taking the previous format to convert int to factor, hence used this one

#Removed the three columns named, "QuestionID" "AAQIVarName" and "PGVarName"
PGQuestion$QuestionID = NULL
PGQuestion$AAQIVarName = NULL
PGQuestion$PGVarName = NULL
```


```{r}
#New Dataframe with Question Table Added
PGSurveyRefined2 = join(PGSurveyRefined, PGQuestion, by=c("QuestionTypeID", "SurveyCategoryID"))
PGSurveyRefined2 <- rename(PGSurveyRefined2, LongTextForQues = LongText, ShortTextForQues = ShortText)

PGSurveyRefined2$AdmitDateLocal = NULL
PGSurveyRefined2$DischargeDateLocal = NULL
PGSurveyRefined2$RecordedDateLocal = NULL

rm(PGSurveyRefined)
rm(PGQuestion)

#Write CSV File
write.csv(PGSurveyRefined2, file = "PGSurveyDomainQuestion.csv") #Contains merged survey content from both Question and Domain

```




